[package]
name = "finch-gen"
version = "0.1.0"
authors = ["Zachary Vacura <zach@hackzzila.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
async = ["tokio", "finch-macro/async"]

[dependencies]
finch-macro = { path = "./macro" }
tokio = { version = "0.2", optional = true }
