name: docs

on: [create, push, release]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Print version
      run: echo ${{ get_version.VERSION }}

    - name: ls
      run: ls

    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: docs-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: docs-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: docs-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Build Docs
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --release --lib --no-deps

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: docs
        path: target/doc